statR version 2.4.0
statistikZH/statR pull request #60
Opened 2024-01-26 08:48 UTC by Thomas-Caspar-Fischer

* redesigned user configurations
* further modularized the functions used to generate worksheets
* revised vignette on creating excel files & regenerated pkgdown

2024-02-05 20:28 UTC, Thomas-Caspar-Fischer commented
The issue related to staged installation has been solved on RStudio Server and Windows systems. The config store file is allocated, and the default configuration is being loaded correctly. The checks are still failing, though. 

Apparently the default config file is not being found during final installation in the GitHub action checks, and I'm not sure why.

2024-02-07 17:40 UTC, philbosch requested changes
Absolut starke Arbeit @Thomas-Caspar-Fischer!
Finde die Doku sehr, sehr gut aufgebaut und zugänglich. Nur kleine Typos/Grammatik-Hickups gefunden.

Falls es für dich funktioniert, gerne ignorieren:
Ich kann leider weder die Vignette noch die Pages builden.
`> devtools::build_site()
Error: 
! in callr subprocess.
Caused by error in `purrr::map(topics, build_reference_topic, pkg = pkg, lazy = lazy, …`:
! In index: 1.
ℹ See `$stdout` for standard output.
Type .Last.error to see the more details.`

2024-02-07 17:40 UTC, philbosch commented on vignettes/Excel-Tabellen.Rmd
> +Das `statR` Package enthält Funktionen zur schnellen Erzeugung von Microsoft Excel-Dateien mithilfe des [openxlsx](https://github.com/awalker89/openxlsx) Pakets. Die Voreinstellungen orientieren sich
```suggestion
Das `statR` Package enthält Funktionen zur schnellen Erzeugung von Microsoft Excel-Dateien mithilfe des [openxlsx](https://github.com/awalker89/openxlsx) Pakets. Die Voreinstellungen orientieren sich am Corporate Design vom Statistischen Amt Kanton Zürich, Anwender können diese Voreinstellungen aber auch an ihre Bedürfnisse anpassen. Entweder, indem sie Anpassungen in den Eingabeargumenten der Funktionen vornehmen, oder indem sie eine eigene Konfiguration anlegen.
```
Fix Typo

2024-02-07 17:40 UTC, philbosch commented on vignettes/Excel-Tabellen.Rmd
> +Mit der Funktion \code{splitXLSX} lässt sich ein beliebiger Datensatz anhand eines Merkmals auf mehrere Arbeitsblätter verteilen. Zur Vereinfachung der Navigation wird im ersten Arbeitsblatt ein Inha
```suggestion
Mit der Funktion \code{splitXLSX} lässt sich ein beliebiger Datensatz anhand eines Merkmals auf mehrere Arbeitsblätter verteilen. Zur Vereinfachung der Navigation wird im ersten Arbeitsblatt ein Inhaltsverzeichnis mit Hyperlinks angelegt. Die Funktion ist besonders geeignet in Fällen, wenn die Variable eine begrenzte Anzahl von Ausprägungen mit intuitiven Bedeutungen hat (zB. Altersklassen, Jahre oder Regionen). 
```
Fix Wording

2024-02-07 17:40 UTC, philbosch commented on vignettes/Excel-Tabellen.Rmd
> +Die Funktion \code{datasetsXLSX} ermöglicht die Erzeugung komplexerer Arbeitsmappen mit mehreren Datensätzen sowie die Einbindung von Grafiken (\code{ggplot}-Objekte oder Pfadangaben zu Bild-Dateien)
```suggestion
Die Funktion \code{datasetsXLSX} ermöglicht die Erzeugung komplexerer Arbeitsmappen mit mehreren Datensätzen sowie die Einbindung von Grafiken (\code{ggplot}-Objekte oder Pfadangaben zu Bild-Dateien). Die Datensätze und Grafiken werden dabei als Liste im Funktionsargument \code{datasets} übergeben. Jeder Eintrag wird in ein neues Arbeitsblatt exportiert und kann wahlweise mit Titeln, Quellangaben und Metadaten versehen werden. Wie in \code{splitXLSX} wird ein Deckblatt mit einem Inhaltsverzeichnis erzeugt. Ferner besteht die Möglichkeit, mit dem Argument \code{metadata_sheet} ein Beiblatt zu erzeugen.
```
Fix Typo

2024-02-07 17:40 UTC, philbosch commented on vignettes/Excel-Tabellen.Rmd
> +Mit den Funktionen der \code{add_attribute}-Familie wird eine alternative Möglichkeit angeboten, \code{datasetsXLSX} zu parametrisieren. Jedes Eingabeobjekt (ob Daten oder Grafiken) kann mit Attribut
Absatz auf Grammatik prüfen: "Philosophie"

2024-02-07 17:40 UTC, philbosch commented on vignettes/Excel-Tabellen.Rmd
> +Um das Paket einem breiteren Anwenderkreis zugänglich zu machen, wurden diverse Aspekte im Design parametrisiert. Textfelder wie Kontaktinformationen können in den Funktionen direkt übersteuert werde
Verständlicher formulieren. YAML beschreiben oder Link. Was bedeutet übersteuern konkret?

2024-02-08 10:40 UTC, Thomas-Caspar-Fischer commented on vignettes/Excel-Tabellen.Rmd
> +Um das Paket einem breiteren Anwenderkreis zugänglich zu machen, wurden diverse Aspekte im Design parametrisiert. Textfelder wie Kontaktinformationen können in den Funktionen direkt übersteuert werde
Im Output hat es einen Print von default.yaml. Den Abschnitt habe ich aber noch so überarbeite, dass klar ist, was mit übersteuern gemeint ist.

2024-02-08 10:52 UTC, Thomas-Caspar-Fischer commented
> Absolut starke Arbeit @Thomas-Caspar-Fischer! Finde die Doku sehr, sehr gut aufgebaut und zugänglich. Nur kleine Typos/Grammatik-Hickups gefunden.
> 
> Falls es für dich funktioniert, gerne ignorieren: Ich kann leider weder die Vignette noch die Pages builden. `> devtools::build_site() Error: ! in callr subprocess. Caused by error in `purrr::map(topics, build_reference_topic, pkg = pkg, lazy = lazy, …`: ! In index: 1. ℹ See `$stdout` for standard output. Type .Last.error to see the more details.`

Das Problem besteht wohl schon eine Weile. Problematisch, weil die pkgdown-Seite den Stand von Version 2.2 reflektiert. 
> pkgdown::build_site() # scheitert
> pkgdown::build_site(examples = FALSE) # läuft

Es besteht noch ein weiteres Problem. Das pkgdown template wird vermutlich nicht verwendet (Fehlermeldung im parenttrace). Ich schau mir das noch an.

2024-02-09 09:19 UTC, merged